#!/usr/bin/env python3
import sys
import helpers
import os

from analyzer import Analyzer
from termcolor import colored

def main():

    if len(sys.argv) != 2:
        sys.exit('Usage: ./tweets @screen_name')

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    analyzer = Analyzer(positives, negatives)
    tweets = helpers.get_user_timeline(sys.argv[1].lstrip('@'), 50)
    if tweets == []:
        sys.exit("None tweets found")
    for tweet in tweets:
       result = analyzer.analyze(tweet)
       if result < 0:
           color = 'red'
       elif result > 0:
           color = 'green'
       else:
           color = 'yellow'
       print(colored("{} {}".format(result, tweet), color))


if __name__ == '__main__':
    main()
